# Generated by Django 5.2.10 on 2026-02-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='livres/')),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
