# Generated by Django 5.2.10 on 2026-02-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livres/'),
        ),
    ]
