# Generated by Django 5.2.10 on 2026-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_livre_description_remove_livre_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
